version: '2.1'

services:

  web:
    build: .
    links:
      - 'db'
    ports:
      - 8088:8088
    depends_on:
      db:
          condition: service_healthy


  db:
    image: mariadb
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: Test_123
      MYSQL_DATABASE: mydb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    
